eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8769

spring:
  application:
    name: zuul-server

zuul:
  routes:
    api-b:
      path: /api-b/**
      serviceId: server-feign
#  host:
#    connect-timeout-millis: 60000
#    socket-timeout-millis: 60000
#
#ribbon:
#  ReadTimeout: 3000
#  ConnectTimeout: 3000
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeout-in-milliseconds: 3000

