eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8765

spring:
  application:
    name: server-feign

feign:
  hystrix:
    enabled: true

#  cloud:
#    loadbalancer:
#      retry:
#        enabled: true
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 30000
#
#ribbon:
#  ReadTimeout: 30000
#  ConnectTimeout: 30000

#feign:
#  client:
#    config:
#      default:
#        connect-timeout: 60000
#        read-timeout: 60000
